---
title: "Pre-taller"
date: "2025-10-08"
format:
  html:
    toc: true
lang: es
---

**Hagamos de revisores del artículo:** 

::: {.callout-important title="Artículo a revisar"}
**Cell (30 de marzo de 2023)** — *Sounds emitted by plants under stress*  
[Enlace al artículo](https://www.cell.com/cell/fulltext/S0092-8674(23)00262-3) — DOI: 10.1016/j.cell.2023.03.009
:::

**[15 minutos] Lee el resumen (texto y gráfico), la introducción y los resultados del artículo para responder a las siguientes preguntas**

#### 1. ¿Cuál es la pregunta de investigación o hipótesis principal?

Estudio del estado de las plantas de tobacco y tomato a partir de los sonidos que estas emiten.

Irene: ¿Las plantas emiten sonidos ultrasónicos al aire cuando son sometidos a estres (sequia o corte)? y si estos sonidos contienen informacion para distinguir el tipo de planta y condicion de tratamiento


#### 2. Define población objetivo, población muestreada, unidad de observación y muestra, tipo de muestreo.

Población: Plantas de tomato y tobacco
Unidad de observación: Planta de tomate o tobacco
Muestra: No esta claro (parece que cogen el mismo numero de cada tipo, el mismo para tomate y tabacco sin agua y asi) Entre 19 y 51
Tipo de muestreo:

Irene: 
Población objetivo: plantas cultivables

Población muestreada: Plantas de tomate y tobacco

Unidad de observación: cada planta de tomate y tabacco considerada en el experimento

Muestra: No estan claros los tamaños muestrales especificos para cada combinacion  planta-tratamiento, en particular no se especifica cuantas fueron registradas  en la camara acustica y cuantas en el invernadero. Esto puede afectar de manera significativa el tipo de test inferencial que se emplea y por tanto la validez del estudio.

Tipo de muestreo: por conveniencia

#### 3. Identifica el tipo de estudio y posibles sesgos y/o efecto confundidor.

Tipo de estudio: experimental casi experimental.

Sesgos: de seleccion o de cobertura, sesgo de tipo de muestreo/eleccion

Confundidores:jardinero, numero de elementos, tipo de muestreo, cambios de temperatura y numero de micros: 2

Irene: 
confundidores: microvariaciones de luz, tamaño de la planta, posiucion de la camara y/o invernadero

sesgo: de cobertura y de medicion, sensibilidad del harware de ultrasonido y filtros de pre-procesamiento  que pueden afectar a los resultados.

#### 4. Define los criterios de inclusión/exclusión para este estudio.

Inclusion: plantas sanas de cada especie, de edades similares.



#### 5. Observa la Figura 1B del artículo (despliega la legenda) ¿qué patrón general observas? ¿Qué indican las barras de error y cómo afectan tu conclusión?. Señala si el gráfico y los test inferenciales son los apropiados.



#### 6. Observa la Figura 1E del artículo. ¿Qué información nos da este gráfico? A la luz de las Figuras 1B y 1E, ¿pueden la frecuencia pico y la intensidad de los eventos acústicos, por sí solas, diferenciar especie y tipo de estrés?


#### 7. Usando los datos de *Tomato–Dry* (Treated, Fig. 1B) —media y barra de error (SEM/SD)— y el tamaño muestral reportado para ese grupo, construye un intervalo de confianza al 95% para la media de clics/hora.

#### 8. Compara la media de clics/hora entre dos grupos (p. ej., *Tomato–Dry* vs. *Tobacco–Dry*). Plantea $H_0$ y $H_1$ de acuerdo a lo que se observa en la figura 1B. Calcula el p-valor. Interpreta el resultado en el contexto biológico del estudio e indica los supuestos que estás adoptando.

#### 9. La legenda de la Figura 1B, pone: “Todos los grupos tratados emiten significativamente más sonidos que todos los grupos control (test de Wilcoxon con corrección de Bonferroni, $p< e^{-6}$).¿Qué significa exactamente esta afirmación y en qué consiste ese test?

<br>

*Nota: Si falta algún $n$ utiliza un supuesto razonable (p.ej. usar n como el mínimo del rango 19-51) y discute cómo podría afectar los IC y la potencia.*